# Generated by Django 4.0.2 on 2022-02-23 10:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import rezervace.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(error_messages={'blank': 'Jméno klienta musí být vyplněno'}, help_text='Zadejte jméno klienta', max_length=50, verbose_name='Jméno klienta')),
                ('prijmeni', models.CharField(error_messages={'blank': 'Příjmení klienta musí být vyplněno'}, help_text='Zadejte příjmení klienta', max_length=50, verbose_name='Příjmení klienta')),
                ('email', models.EmailField(error_messages={'blank': 'Pole nesmí být prázdné', 'invalid': 'Neplatná e-mailová adresa', 'unique': 'E-mailová adresa musí být jedinečná'}, help_text='Zadejte e-mail klienta', max_length=254, unique=True, verbose_name='Email klienta')),
                ('telefon', models.CharField(blank=True, help_text='Zadejte telefon v podobě: +420 777 777 777', max_length=16, validators=[django.core.validators.RegexValidator('^[+]\\d{3}( \\d{3}){3}$', 'Nesprávně zadané telefonní číslo')], verbose_name='Telefon klienta')),
            ],
            options={
                'verbose_name': 'Klient',
                'verbose_name_plural': 'Klienti',
                'ordering': ['prijmeni', 'jmeno'],
            },
        ),
        migrations.CreateModel(
            name='Vybaveni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(help_text='Zadejte název vybavení', max_length=30, verbose_name='Název vybavení')),
                ('symbol', models.ImageField(upload_to='symbols', verbose_name='Grafický symbol')),
            ],
            options={
                'verbose_name': 'Vybavení',
                'verbose_name_plural': 'Vybavení',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Ubytovani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oznaceni', models.CharField(help_text='Zadejte vhodné označení ubytování', max_length=100, verbose_name='Označení ubytování')),
                ('adresa', models.CharField(help_text='Zadejte ulici a číslo popisné (orientační)', max_length=100, verbose_name='Adresa')),
                ('misto', models.CharField(help_text='Zadejte název města nebo obce', max_length=50, verbose_name='Město/obec')),
                ('psc', models.PositiveIntegerField(help_text='Zadejte poštovní směrovací číslo (bez mezery)', validators=[django.core.validators.RegexValidator('^\\d{3} +\\d{2}$', 'Nesprávně zadané poštovní směrovací číslo')], verbose_name='PSČ')),
                ('kontakt', models.CharField(help_text='Zadejte jméno a příjmení kontaktní osoby', max_length=50, verbose_name='Kontaktní osoba')),
                ('telefon', models.CharField(error_messages={'blank': 'Telefonní číslo musí být vyplněno'}, help_text='Zadejte telefon v podobě: +420 777 777 777', max_length=16, validators=[django.core.validators.RegexValidator('^[+]\\d{3}( \\d{3}){3}$', 'Nesprávně zadané telefonní číslo')], verbose_name='Telefon')),
                ('email', models.EmailField(error_messages={'blank': 'Pole nesmí být prázdné', 'invalid': 'Neplatná e-mailová adresa', 'unique': 'E-mailová adresa musí být jedinečná'}, help_text='Zadejte e-mail ubytování (kontaktní osoby)', max_length=254, unique=True, verbose_name='Email')),
                ('popis', models.TextField(help_text='Zadejte podrobnější informace o ubytování', verbose_name='Popis ubytování')),
                ('pocet_pokoju', models.PositiveSmallIntegerField(help_text='Zadejte číselný údaj o počtu pokojů', verbose_name='Počet pokojů')),
                ('vybaveni', models.ManyToManyField(to='rezervace.Vybaveni')),
            ],
            options={
                'verbose_name': 'Ubytování',
                'verbose_name_plural': 'Ubytování',
                'ordering': ['oznaceni'],
            },
        ),
        migrations.CreateModel(
            name='Rezervace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zacatek_pobytu', models.DateField(help_text='Zadejte datum začátku pobytu', verbose_name='Začátek pobytu')),
                ('konec_pobytu', models.DateField(help_text='Zadejte datum konce pobytu', verbose_name='Konec pobytu')),
                ('pocet_osob', models.PositiveIntegerField(help_text='Zadejte požadovaný počet ubytovaných osob (max. 9)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='Počet osob')),
                ('info', models.TextField(blank=True, help_text='Zde můžete zadat další informace nebo požadavky', verbose_name='Informace od klienta')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezervace.klient', verbose_name='Jméno klienta')),
                ('ubytovani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezervace.ubytovani', verbose_name='Název ubytování')),
            ],
            options={
                'verbose_name': 'Rezervace',
                'verbose_name_plural': 'Rezervace',
                'ordering': ['zacatek_pobytu', 'klient'],
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotka', models.ImageField(upload_to=rezervace.models.get_image_path, verbose_name='Fotografie')),
                ('popis', models.CharField(max_length=200, verbose_name='Popis fotky')),
                ('ubytovani', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rezervace.ubytovani', verbose_name='Název ubytování')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fota',
                'ordering': ['popis'],
            },
        ),
    ]
