# Generated by Django 4.0.2 on 2022-02-23 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubytovani',
            name='psc',
            field=models.PositiveIntegerField(help_text='Zadejte poštovní směrovací číslo (bez mezery)', validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Nesprávně zadané poštovní směrovací číslo')], verbose_name='PSČ'),
        ),
    ]
