# Generated by Django 4.0.4 on 2023-03-26 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rezervace', '0002_alter_ubytovani_psc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hodnoceni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pozitiva', models.TextField(blank=True, error_messages={'max_length': 'Text nesmí být delší než 1000 znaků'}, help_text='Vypište kladné stránky ubytování o maximální délce 1000 znaků', max_length=1000, null=True, verbose_name='Pozitiva')),
                ('negativa', models.TextField(blank=True, error_messages={'max_length': 'Text nesmí být delší než 1000 znaků'}, help_text='Vypište záporné stránky ubytování (max. 1000 znaků)', max_length=1000, null=True, verbose_name='Negativa')),
                ('znamka', models.PositiveSmallIntegerField(choices=[(1, 'výborné'), (2, 'chvalitebné'), (3, 'dobré'), (4, 'dostatečné'), (5, 'nedostatečné')], error_messages={'blank': 'Hodnocení známkou musí být vyplněno'}, help_text='Zadej hodnocení jako ve škole', verbose_name='Známka')),
                ('datum_recenze', models.DateField(auto_now_add=True, verbose_name='Datum recenze')),
                ('klient', models.ForeignKey(error_messages={'blank': 'Jméno klienta musí být zvoleno'}, on_delete=django.db.models.deletion.CASCADE, to='rezervace.klient', verbose_name='Hodnocení klienta')),
                ('ubytovani', models.ForeignKey(error_messages={'blank': 'Ubytování musí být vybráno'}, on_delete=django.db.models.deletion.CASCADE, to='rezervace.ubytovani', verbose_name='Název ubytování')),
            ],
            options={
                'verbose_name': 'Hodnocení pobytu',
                'verbose_name_plural': 'Hodnocení pobytu',
                'ordering': ['ubytovani', '-datum_recenze'],
            },
        ),
    ]
